### ISSUE TITLE
Setting up the environment

### ISSUE THREAD

**Issue by HenryBol** [groningenml/ktitanic#1]
- [x] Henry: add Clemens to Kaggle Team GroningenML

**Comment by HenryBol** [comment]
I set up a test code in VSC; couple of questions:
- [x] #2 virtual environment statement: should it be included at the top of the code 
- [x] extension py or ipynb?
- [x] syncing in VSC does not yet show the test-file in this Github environment

**Comment by clemens-tolboom** [comment]
## requirements.txt

I've installed `pipenv` and you have probably installed `anaconda`. Both tools are environment tools to prepare before running code.

I can run `pipenv install --requirements requirements.txt` to configure the environment.

## Notebook (.ipynb)

I run `pipenv run jupyter notebook` which makes the notebook code run in the correct environment

## Plain python (*.py)

I have to run `pipenv shell` then `python my-script.py` or use my IDE (PyCharm) which is aware of pipenv. iirc VSCode can do that too but have to check.

## git push/pull/fetch

- Syncing is check upstream aka code on github
- push will put your file(s) on github
- pull will sync your local files with those from github.

**Comment by clemens-tolboom** [comment]
It's maybe better to split issues into separate ones so we can close each at will
