### ISSUE TITLE
VSC and Jupyter

### ISSUE THREAD

**Issue by HenryBol** [groningenml/ktitanic#3]
Are we importing and exporting .ipynb to .py in VSC?
![image](https://user-images.githubusercontent.com/43902934/57775071-807d5d80-771c-11e9-9788-c3a738a38a30.png)

**Comment by clemens-tolboom** [comment]
That a nice feature.

I use VS Code to edit, run and debug `*.py` code.

And `jupyter notebook` to run and edit my `*.ipynb` code.
